#!/usr/bin/python

import argparse
import dlinputs as dli

parser = argparse.ArgumentParser("Display info about an input module.")
parser.add_argument("-i", "--input", default="zpull://*:10000")
parser.add_argument("-o", "--output", default="zpub://*:10001")
args = parser.parse_args()

inputs = dli.Comms(args.input, pack=False, encode=False)
outputs = dli.Comms(args.output, pack=False, encode=False)

count = 0
while True:
    if count%1000==0: print count
    data = inputs.recv()
    outputs.send(data)
    count += 1
