#!/usr/bin/python

import matplotlib
# matplotlib.use("GTK")

from pylab import *
rc("image", cmap="hot")
import pylab
import os
import imp
import glob
import numpy as np
import argparse
from dlpipes import io
import time

parser = argparse.ArgumentParser("Display info about model or save network.")
parser.add_argument("model")
args = parser.parse_args()

model = io.load_net(args.model)
print model
