#!/usr/bin/python

import argparse
import glob
import imp
import os
import re
import time

import matplotlib
import numpy as np
import pylab
from pylab import *

import dlinputs as dli
from dlinputs import filters
from dlinputs import gopen
from dlinputs import utils
from dlinputs import zcom

# matplotlib.use("GTK")

rc("image", cmap="hot")

parser = argparse.ArgumentParser("Display info about an input module.")
parser.add_argument("-c", "--code", default="filters.shuffle()")
parser.add_argument("-e", "--every", type=int, default=1000)
parser.add_argument("input")
parser.add_argument("output")
args = parser.parse_args()

source = gopen.open_source(args.input)
sink = gopen.open_sink(args.output)

pipeline = eval("filters.compose({})".format(args.code))
transformed = pipeline(source)

for i, sample in enumerate(transformed):
    if i%1000==0: print i
    sink.write(sample)
